# Set systemd-resolved config
- name: Copy over resolved config
  copy:
    src: resolved.conf
    dest: /etc/systemd/
  register: resolved
- name: Create symbolic link for resolved config
  file:
    src: /run/systemd/resolve/resolv.conf
    dest: /etc/resolv.conf
    state: link
- name: Restart systemd resolved
  when: resolved.changed
  systemd:
    name: systemd-resolved
    state: restarted

- name: start cloudflared
  docker_container:
    name: cloudflared
    image: visibilityspots/cloudflared:latest
    network_mode: host
    env:
      ADDRESS: "::"

- name: start pihole
  docker_container:
    name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "127.0.0.1:8888:80/tcp"
    env:
      TZ: Europe/Vienna
      PIHOLE_DNS_: "127.0.0.1#5054;1.1.1.1;1.0.0.1;2606:4700:4700::1111"
      WEBPASSWORD: "{{ pihole_pw }}"
    volumes:
      - "{{ services_root }}pihole/etc-pihole:/etc/pihole"
      - "{{ services_root }}pihole/etc-dnsmasq.d:/etc/dnsmasq.d"
