- hosts: server
  gather_facts: no
  user: root
  vars_files:
    - ./vars/main.yml
  tasks:
    # Install deps
    - name: install pacman packages
      pacman:
        # update_cache: yes
        name:
          - docker
          - docker-compose
          - python-pip
    - name: install python dependencies
      pip:
        name:
          - docker
          - docker-compose

    - name: Setup pihole
      include_tasks: tasks/pihole.yml

    # Clean up
    - name: Prune everything
      docker_prune:
        containers: yes
        images: yes
        networks: yes
        volumes: yes
        builder_cache: yes
